"""Morning Radar history and schedule for Trader_7_12 Cloud.

The recorder does not calculate market data. It only stores the production
snapshot already generated by CloudMarketDataEngine and derives transparent
morning-to-morning deltas from fields already present in that snapshot.

Schedule is Moscow time:
07:00, 07:15, 07:30, 08:00, 09:00, 09:45, 09:50.
"""
from __future__ import annotations

import json
import os
import tempfile
from datetime import datetime, date
from pathlib import Path
from zoneinfo import ZoneInfo

MSK = ZoneInfo("Europe/Moscow")
MORNING_SLOTS = ("07:00", "07:15", "07:30", "08:00", "09:00", "09:45", "09:50")


def _num(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _pct_delta(current, previous):
    current = _num(current)
    previous = _num(previous)
    if current is None or previous is None or abs(previous) < 1e-12:
        return None
    return round((current / previous - 1.0) * 100.0, 1)


def _interest_state(row, previous):
    if previous is None:
        return "BASE"
    recent_delta = _pct_delta(row.get("recent_money"), previous.get("recent_money"))
    rpm_delta = _pct_delta(row.get("money_per_minute"), previous.get("money_per_minute"))
    accel = _num(row.get("money_acceleration"))
    if (recent_delta is not None and recent_delta >= 10.0) or (
        rpm_delta is not None and rpm_delta >= 10.0
    ) or (accel is not None and accel >= 25.0):
        return "↑"
    if (recent_delta is not None and recent_delta <= -10.0) or (
        rpm_delta is not None and rpm_delta <= -10.0
    ) or (accel is not None and accel <= -25.0):
        return "↓"
    return "→"


def _short_watch(regime, row):
    regime = str(regime or "NEUTRAL").upper()
    change = _num(row.get("change_percent"))
    rs = _num(row.get("relative_strength"))
    if regime == "UP":
        return bool((rs is not None and rs < 0.0) or (change is not None and change <= 0.0))
    if regime == "DOWN":
        return bool((rs is not None and rs > 0.0) or (change is not None and change >= 0.0))
    return False


class MorningRadarService:
    """Persistent, date-keyed morning history built from production snapshots."""

    def __init__(self, storage_path: str | None = None):
        default = Path(
            os.getenv(
                "TRADER_MORNING_RADAR_PATH",
                str(Path(__file__).resolve().parent / "data" / "morning_radar.json"),
            )
        )
        self.path = Path(storage_path or default)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._data = self._load()

    def _load(self):
        if not self.path.exists():
            return {"version": 1, "days": {}}
        try:
            return json.loads(self.path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return {"version": 1, "days": {}}

    def _save(self):
        payload = json.dumps(self._data, ensure_ascii=False, indent=2)
        fd, temp_path = tempfile.mkstemp(
            prefix=".morning_radar_", suffix=".json", dir=str(self.path.parent)
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temp_path, self.path)
        finally:
            try:
                os.unlink(temp_path)
            except FileNotFoundError:
                pass

    @staticmethod
    def _now():
        return datetime.now(MSK)

    def due_slot(self, now: datetime | None = None):
        now = now.astimezone(MSK) if now else self._now()
        current_minutes = now.hour * 60 + now.minute
        best = None
        best_distance = 999
        for slot in MORNING_SLOTS:
            hour, minute = map(int, slot.split(":"))
            distance = abs(current_minutes - (hour * 60 + minute))
            if distance <= 2 and distance < best_distance:
                best = slot
                best_distance = distance
        return best

    def record_if_due(self, snapshot: dict, now: datetime | None = None):
        now = now.astimezone(MSK) if now else self._now()
        slot = self.due_slot(now)
        if slot is None:
            return None
        day_key = now.date().isoformat()
        day = self._data.setdefault("days", {}).setdefault(day_key, {"snapshots": {}})
        if slot in day["snapshots"]:
            return day["snapshots"][slot]

        radar = list(snapshot.get("radar") or [])
        previous = None
        ordered = sorted(day["snapshots"].items())
        if ordered:
            previous = ordered[-1][1]

        previous_rows = {
            str(item.get("ticker") or item.get("spot_ticker")): item
            for item in (previous or {}).get("stocks", [])
        }
        regime = (snapshot.get("radar_diagnostics") or {}).get("market_regime", "NEUTRAL")
        diagnostics = snapshot.get("radar_diagnostics") or {}
        countertrend = list(diagnostics.get("countertrend_watch") or [])
        stocks = []
        for rank, row in enumerate(radar, 1):
            ticker = str(row.get("spot_ticker") or "")
            old = previous_rows.get(ticker)
            stocks.append({
                "rank": rank,
                "ticker": ticker,
                "change_percent": row.get("change_percent"),
                "relative_strength": row.get("relative_strength"),
                "money_per_minute": row.get("money_per_minute"),
                "recent_money": row.get("recent_money"),
                "money_acceleration": row.get("money_acceleration"),
                "directional_score": row.get("directional_score"),
                "signal": row.get("signal"),
                "signal_probability": row.get("signal_probability"),
                "interest": _interest_state(row, old),
                "recent_money_delta_pct": _pct_delta(
                    row.get("recent_money"), (old or {}).get("recent_money")
                ),
                "rpm_delta_pct": _pct_delta(
                    row.get("money_per_minute"), (old or {}).get("money_per_minute")
                ),
                "short_watch": _short_watch(regime, row),
                "short_watch_persistence": (
                    int((old or {}).get("short_watch_persistence") or 0) + 1
                    if (old or {}).get("short_watch") else 0
                ),
            })

        existing_tickers = {str(x.get("ticker")) for x in stocks}
        for candidate in countertrend:
            ticker = str(candidate.get("ticker") or "")
            if not ticker or ticker in existing_tickers:
                continue
            old = previous_rows.get(ticker)
            stocks.append({
                "rank": len(stocks) + 1,
                "ticker": ticker,
                "change_percent": candidate.get("change_percent"),
                "relative_strength": candidate.get("relative_strength"),
                "money_per_minute": candidate.get("money_per_minute"),
                "recent_money": candidate.get("recent_money"),
                "money_acceleration": candidate.get("money_acceleration"),
                "directional_score": candidate.get("directional_score"),
                "signal": candidate.get("signal"),
                "signal_probability": candidate.get("signal_probability"),
                "interest": _interest_state(candidate, old),
                "recent_money_delta_pct": _pct_delta(
                    candidate.get("recent_money"), (old or {}).get("recent_money")
                ),
                "rpm_delta_pct": _pct_delta(
                    candidate.get("money_per_minute"), (old or {}).get("money_per_minute")
                ),
                "short_watch": True,
                "short_watch_persistence": (
                    int((old or {}).get("short_watch_persistence") or 0) + 1
                    if (old or {}).get("short_watch") else 1
                ),
                "countertrend_reason": candidate.get("reason"),
            })
            existing_tickers.add(ticker)

        entry = {
            "slot": slot,
            "recorded_at": now.isoformat(),
            "market_regime": regime,
            "benchmark": (snapshot.get("radar_diagnostics") or {}).get("benchmark"),
            "benchmark_change_percent": (snapshot.get("radar_diagnostics") or {}).get(
                "benchmark_change_percent"
            ),
            "coverage_percent": (snapshot.get("radar_diagnostics") or {}).get(
                "coverage_percent"
            ),
            "stocks": stocks,
            "countertrend_watch": countertrend,
            "futures_oi": list(snapshot.get("futures_oi") or []),
            "futures_diagnostics": dict(snapshot.get("futures_diagnostics") or {}),
            "timing": dict(snapshot.get("timing") or {}),
        }
        day["snapshots"][slot] = entry
        day["last_slot"] = slot
        self._save()
        return entry

    def latest(self, day: date | None = None):
        key = (day or self._now().date()).isoformat()
        day_data = self._data.get("days", {}).get(key)
        if not day_data:
            return None
        snapshots = day_data.get("snapshots", {})
        if not snapshots:
            return None
        slot = sorted(snapshots)[-1]
        return snapshots[slot]

    def as_dict(self, day: date | None = None):
        key = (day or self._now().date()).isoformat()
        day_data = self._data.get("days", {}).get(key, {})
        snapshots = day_data.get("snapshots", {})
        latest = snapshots[sorted(snapshots)[-1]] if snapshots else None
        return {
            "status": "READY" if snapshots else "NO_DATA",
            "date": key,
            "slots": list(MORNING_SLOTS),
            "captured_slots": sorted(snapshots),
            "complete": "09:50" in snapshots,
            "latest": latest,
            "history": [snapshots[k] for k in sorted(snapshots)],
        }

    def due_slots(self):
        return MORNING_SLOTS
